### ISSUE TITLE
Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLKey

### ISSUE THREAD

**Issue by KarrePrakash** [iwasrobbed/Forecastr#23]
I implemented SSL for iOS Application first time and facing following in rest call completionHandler.

Optional<NSError>
  - Some : Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLKey=https://devrm.getquickride.com:8443/dishaapiserver/rest/QRUser/login?&pwd=p&userId=9491523886, NSErrorFailingURLStringKey=https://devrm.getquickride.com:8443/dishaapiserver/rest/QRUser/login?&pwd=p&userId=9491523886, NSLocalizedDescription=cancelled}

Block of code using for SSL pinning.

let pathToCert = NSBundle.mainBundle().pathForResource("quickride_ssl_der", ofType: "cer")
        let localCertificate:NSData = NSData(contentsOfFile: pathToCert!)!
        
        let serverTrustPolicy = ServerTrustPolicy.PinCertificates(
          certificates: [SecCertificateCreateWithData(nil, localCertificate)!],
          validateCertificateChain: true,
          validateHost: true)
        
        let serverTrustPolicies = ["devrm.getquickride.com": serverTrustPolicy]
        
        alamoFireManager =  Manager(configuration: NSURLSessionConfiguration.defaultSessionConfiguration(),serverTrustPolicyManager: ServerTrustPolicyManager(policies: serverTrustPolicies))
     
      
      alamoFireManager!.request(.GET, url,parameters: params).responseJSON(){
        response in
        AppDelegate.getAppDelegate().log.debug("Request: \(response.request); Response: \(response.response); Value: \(response.result)")

**Comment by iwasrobbed** [comment]
@KarrePrakash You should probably check on Alamofire's (or AFNetworking's) repo: https://github.com/Alamofire/Alamofire / https://github.com/AFNetworking/AFNetworking
